name: Build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  build:
    name: Build packages
    runs-on: macos-latest
    steps:
      - name: Install formula
        uses: actions/checkout@v4
        run: |
          brew install -s Formula/snowcli.rb
      - name: Check snow commands
        run: |
          snow --help
