name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build packages
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install formula
        run: |
          brew install -s Formula/snowcli.rb
      - name: Check snow commands
        run: |
          snow --help
