name: Build

on: [push]

jobs:
  build:
    name: Build packages
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install formula
        run: |
          brew install --formula -s Formula/snowcli.rb
          brew uninstall snowcli
          brew install --formula -s Formula/snowflake-cli.rb
      - name: Check snow commands
        run: |
          snow --help
